-- Every scrape pipeline already classifies *why* an extracted candidate got dropped
-- (classifyRejection in sourceConfigs.ts: missing URL, country mismatch, keyword mismatch, or the
-- anti-fabrication source-content check) but only ever kept an aggregate tally, since a rejected
-- candidate never becomes a `tenders` row. This captures the actual candidates so "was my keyword
-- list too strict?" is answerable by looking at real near-misses, not just a count.
create table if not exists rejected_tenders (
  id bigint generated by default as identity primary key,
  job_id uuid references scrape_jobs(id) on delete cascade,
  tender_type text,
  title text not null,
  source_url text,
  organization text,
  category text,
  location text,
  reason text not null,
  rejected_at timestamptz not null default now()
);

create index if not exists rejected_tenders_job_id_idx on rejected_tenders(job_id);

-- Rejected candidates are diagnostic, not permanent records — keeping them bounded so this doesn't
-- grow unbounded alongside every scrape run forever.
create index if not exists rejected_tenders_rejected_at_idx on rejected_tenders(rejected_at);
